export const positions: string[] = [
  "Goalkeeper",
  "Defender",
  "Midfielder",
  "Forward",
];

export const nations: string[] = [
  "Japanese",
  "Portuguese",
  "Spanish",
  "Indian",
  "Italian",
  "Russian",
  "French",
  "German",
  "Canadian",
  "Mexican",
  "South African",
  "Australian",
  "British",
  "Irish",
  "Egyptian",
  "Kenyan",
  "Nigerian",
  "Saudi Arabian",
  "Israeli",
  "Korean",
  "Indonesian",
  "Vietnamese",
  "Greek",
  "Turkish",
  "Swedish",
  "Norwegian",
  "Danish",
  "Peruvian",
  "Chilean",
  "Colombian",
  "Jamaican",
  "Cuban",
  "New Zealander",
  "Fijian",
  "Pakistani",
  "Bangladeshi",
  "Sri Lankan",
  "Afghan",
  "Iranian",
  "Iraqi",
  "Syrian",
  "South Sudanese",
  "Ethiopian",
  "Moroccan",
  "Costa Rican",
  "Morocco",
  "French",
  "Spanish",
  "Brazilian",
  "Argentinian",
  "Guinea-Bissau",
  "Dutch",
  "Senegal",
];

export const nationalities = nations.filter((value, index, self) => {
  return self.indexOf(value) === index;
});
